server:
  port: 8081
  error:
    include-message: always
spring:
  data:
    mongodb:
      uri: mongodb+srv://administrator:9exM6fWPUpdq7xFI@nttdata.m70zc.mongodb.net/msbanktransation
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9091/eureka/   
      
microservices:
  client:
    base-url: http://localhost:8083
    base-path: /api/v1
    end-point:
      client: ${microservices.client.base-path}/clients
      plan: ${microservices.client.base-path}/plans
  bank-account:
    base-url: http://localhost:8080
    base-path: /api/v1
    end-point:
      bank-account: ${microservices.bank-account.base-path}/bank-accounts
