server:
  port: 8080
  error:
    include-message: always
spring:    
  data:
    mongodb:
      uri: mongodb+srv://administrator:9exM6fWPUpdq7xFI@nttdata.m70zc.mongodb.net/msbankaccount
      #host: localhost
      #port: 27017
      #database: banktransactiondb
      #uri: mongodb://localhost:27017/bankaccountdb
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9091/eureka/      

api-gateway:
  base:
    url: http://localhost:9092
    path: /api/v1
  routes:
    ms-client:
      client: ${api-gateway.base.url}${api-gateway.base.path}/clients
      plan: ${api-gateway.base.url}${api-gateway.base.path}/plans
    ms-product:
      product: ${api-gateway.base.url}${api-gateway.base.path}/products
      category: ${api-gateway.base.url}${api-gateway.base.path}/categories
    ms-transaction:    
      credit: ${api-gateway.base.url}${api-gateway.base.path}/credits
