server:
  port: 8088
  error:
    include-message: always
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/buybitcoindb

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9091/eureka/

kafka:
  server:
    host: 127.0.0.1:9092
