server:
  port: 8086
  error:
    include-message: always
spring:    
  data:
    mongodb:
      uri: mongodb+srv://administrator:9exM6fWPUpdq7xFI@nttdata.m70zc.mongodb.net/mscard
      
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9091/eureka/  

api-gateway:
  base:
    url: http://localhost:9092
    path: /api/v1
  routes:
    ms-bank-account:
      account: ${api-gateway.base.url}${api-gateway.base.path}/bank-accounts
