server:
  port: 8085
  error:
    include-message: always
  data:
    mongodb:
      uri: mongodb+srv://administrator:9exM6fWPUpdq7xFI@nttdata.m70zc.mongodb.net/msproduct
      
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9091/eureka/      
